kind: pipeline
name: default

steps:
  - name: install
    image: node
    commands:
      - yarn install
  - name: build_app
    image: node
    commands:
      - yarn build:app
  - name: build_lib
    image: node
    commands:
      - yarn build
  - name: test:unit
    image: node
    commands:
      - yarn test:unit
  - name: lint
    image: node
    commands:
      - yarn lint
#  - name: publish_release
#    image: plugins/github-release
#    settings:
#      api_key:
#        from_secret: github_token
#      files: dist/*
#    when:
#      event: tag
#  - name: publish_npm
#    image: plugins/npm
#    when:
#      event: tag
#    settings:
#      token:
#        from_secret: npm_token
